---
pagetitle: "{{< meta website.title >}}"
title: "Organisation"
subtitle: "Theory and Methods Challenge Fortnight, Alan Turing Institute" 
title-block-banner: "#495057"
---


We have assembled an interdisciplinary team of 12 world-leaders working in Information Visualization, Statistical Modelling, Human Computer Interaction, Communication Studies and Geography.

Challenge Leads:

* [Cagatay Turkay](https://warwick.ac.uk/fac/cross_fac/cim/people/cagatay-turkay/), Professor of Visual Data Science, Centre for Interdisciplinary Methodologies, University of Warwick
* [Roger Beecham](https://www.roger-beecham.com/),  Associate Professor of Visual Data Science, School of Geography, University of Leeds

Challenge Organisers:

* [Jessica Hullman](http://users.eecs.northwestern.edu/~jhullman/), Ginni Rometty Associate Professor, Computer Science and Communication Studies, Northwestern University 
* [Levi Wolf](https://www.ljwolf.org/), Senior Lecturer in Quantitative Human Geography,  School of Geographical Sciences, University of Bristol
* [Di Cook](http://www.dicook.org/), Professor of Business Analytics, Econometrics and Business Statistics, Monash University

Chellege team Members (to be finalised):
